INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Explore a galáxia em uma série épica de RPGs de ação e escolhas impactantes.', 'Em Mass Effect, você assume o papel do Comandante Shepard, viajando por diferentes planetas, tomando decisões morais e enfrentando uma ameaça cósmica que coloca a galáxia em risco. Com jogabilidade de tiro e uma narrativa envolvente, a trilogia é uma das mais amadas da indústria de jogos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Uma imersiva aventura no Velho Oeste, onde escolhas e ações definem o destino do protagonista.', 'Red Dead Redemption 2 segue a história de Arthur Morgan, um membro da gangue Van der Linde. Situado no final do século XIX, o jogo oferece uma vasta exploração do Velho Oeste, com missões emocionantes, personagens ricos e um mundo aberto detalhado, onde suas escolhas moldam a narrativa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Uma jornada épica de caça a monstros e escolhas morais, ambientada em um mundo repleto de fantasia.', 'Em The Witcher 3, você controla Geralt de Rivia, um caçador de monstros, que se vê no meio de uma guerra e caçando a misteriosa Ciri. O jogo é conhecido por seu mundo aberto, histórias profundas e combate desafiante, oferecendo uma experiência rica e imersiva de RPG.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Um jogo desafiador que mistura ação e furtividade, ambientado no Japão feudal.', 'Sekiro: Shadows Die Twice coloca o jogador no papel de um shinobi em busca de vingança. Com mecânicas desafiadoras de combate e um sistema de progressão único, o jogo desafia os jogadores a dominar a espada, furtividade e habilidades de sobrevivência.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Lute pela honra e liberdade na era feudal do Japão, enquanto um samurai tenta salvar sua terra natal.', 'Em Ghost of Tsushima, você assume o papel de Jin Sakai, um samurai que se vê forçado a adotar métodos não tradicionais para enfrentar a invasão mongol. O jogo combina combate brutal com uma narrativa rica e um mundo aberto impressionante que captura a beleza e a cultura do Japão feudal.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Aventura clássica de plataforma onde Mario busca resgatar Princess Peach no Reino dos Cogumelos.', 'Super Mario World é um dos jogos de plataforma mais influentes de todos os tempos, onde Mario deve viajar por diversas ilhas e enfrentar Bowser para salvar a Princesa Peach. Com controles suaves, mundos criativos e inimigos carismáticos, o jogo é uma verdadeira lenda dos jogos de plataforma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Uma jornada profunda por um mundo subterrâneo cheio de mistérios e criaturas perigosas.', 'Hollow Knight é um metroidvania que desafia os jogadores a explorar as profundezas de Hallownest, enfrentando inimigos complexos e resolvendo enigmas. O jogo é conhecido por seu estilo de arte impressionante e uma jogabilidade desafiante e gratificante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma bela e tocante jornada em um mundo de plataforma 2D repleto de emoções e desafios.', 'Ori and the Blind Forest é um jogo de plataforma que segue a história de Ori, uma criatura pequena que deve salvar sua floresta do caos. Com gráficos deslumbrantes, uma trilha sonora emocional e uma jogabilidade desafiante, o jogo é uma verdadeira obra de arte.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Um jogo de plataforma com estilo retrô e combates intensos contra chefões, inspirado nos desenhos animados dos anos 1930.', 'Cuphead é conhecido por seu estilo de arte único, que lembra desenhos animados antigos. Os jogadores enfrentam chefões desafiadores em uma série de batalhas intensas, com uma dificuldade elevada que testa a paciência e as habilidades de reação do jogador.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Ajude Sonic a salvar o futuro e derrotar o Dr. Robotnik em uma aventura cheia de velocidade.', 'Sonic CD é um jogo de plataforma rápido onde Sonic viaja no tempo para impedir o Dr. Robotnik de dominar o futuro. O jogo é conhecido por seus gráficos vibrantes, trilha sonora marcante e jogabilidade única que introduz mecânicas de viagem no tempo.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4)